# Generated by Django 5.0 on 2023-12-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Политика',
            new_name='Категория',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Прочее',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Техника и технологии',
        ),
    ]
