# Generated by Django 5.0 on 2024-01-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_политика_category_категория_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Заголовок',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
    ]
