# Generated by Django 5.0 on 2024-01-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_заголовок_post_title_remove_category_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Содержание',
            new_name='description',
        ),
    ]
