# Generated by Django 5.0 on 2024-01-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_содержание_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=100, upload_to='media/', width_field=100),
        ),
    ]
